# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20171120_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.Profile'),
        ),
    ]
